Training/08 observers and plugins
jlboban/m2 pull request #10
Opened 2021-09-14 07:16 UTC by jlboban

2021-09-14 10:15 UTC, tnikcevs approved these changes
u svrhu treninga nije prebitno, ali komentare na plugine i observere obavezno stavit. prvo zbog sebe jer ćete vrlo vjerojatno to trebati popravljati ili adjustati nakon nekog vremena, drugo zbog drugih da nebuge vrijeme na saznavanje konteksta ili PR-ove

2021-09-14 10:15 UTC, tnikcevs commented on app/code/Inchoo/Sample08/Plugin/RecurringDataPlugin.php
> +// @codingStandardsIgnoreFile
uvijek komentar zašto je ignorano, bilo file, linija ili chunk

2021-09-14 10:35 UTC, tnikcevs commented on app/code/Inchoo/Sample08/Plugin/ProductRepositoryPlugin.php
> +        ?int $storeId = null,
da li su ti potrebni svi ovi argumenti?

2021-09-14 10:39 UTC, tnikcevs requested changes
plugine get i getbyid pogledaj jel ti trebaju svi oni argumenti ili su redundantni

2021-09-15 06:19 UTC, tnikcevs approved these changes

2021-09-15 06:58 UTC, ivanmatozan requested changes

2021-09-15 06:58 UTC, ivanmatozan commented on app/code/Inchoo/Sample08/Plugin/CollectionPlugin.php
> +namespace Inchoo\Sample08\Plugin;
na prvu je teško iz imena i dir putanje vidjeti za koji collection plugin. Možeš ovako napraviti:
`Inchoo\Sample08\Plugin\Catalog\Model\ResourceModel\Product\CollectionPlugin`
ili
`Inchoo\Sample08\Plugin\Model\ResourceModel\Product\CollectionPlugin`
ili
`Inchoo\Sample08\Plugin\ProductCollectionPlugin`

2021-09-15 06:58 UTC, ivanmatozan commented on app/code/Inchoo/Sample08/Plugin/CollectionPlugin.php
> +        return [false, $logQuery];
radi i ovo, ali u zadataku piše "set the printQuery argument to false if it is not already"

2021-09-15 06:58 UTC, ivanmatozan commented on app/code/Inchoo/Sample08/Plugin/RecurringDataPlugin.php
> +namespace Inchoo\Sample08\Plugin;
na prvu mi nije jasno o kojem se RecurringData radi (iz kojeg modula). Nparavi izmjenu namespacea (dir putanje)

2021-09-15 06:58 UTC, ivanmatozan commented on app/etc/config.php
>          'Magento_Variable' => 1,
ne vezane stvari u PR-u, makni to

2021-09-15 06:58 UTC, ivanmatozan commented on app/code/Inchoo/Sample08/etc/di.xml
> +    </type>
jesi siguran da ti se pokreće prije `add_stock_information`?

2021-09-16 12:35 UTC, ivanmatozan approved these changes

2021-09-16 13:03 UTC, merged