Training/03 magento UI
jlboban/m2 pull request #5
Opened 2021-08-11 11:24 UTC by jlboban

2021-08-13 08:01 UTC, tnikcevs requested changes

2021-08-13 08:01 UTC, tnikcevs commented on app/code/Inchoo/Sample03/view/frontend/layout/inchoo_sample03_index_weight.xml
> +            <block name="inchoo_sample03_weight" class="Inchoo\Sample03\Block\Weight" template="Inchoo_Sample03::custom/weight.phtml">
nepotrebno imati definiran i kreiran block ako nema posebne logike u njemu, viewmodel dovoljan

2021-08-31 11:10 UTC, ivanmatozan requested changes

2021-08-31 11:10 UTC, ivanmatozan commented on app/code/Inchoo/Sample03/view/frontend/templates/custom/weight.phtml
> +            <?php // phpcs:ignore ?>
za čega je ovaj ignore?

2021-08-31 11:10 UTC, ivanmatozan commented on app/design/frontend/Inchoo/custom/Inchoo_Sample03/layout/inchoo_sample03_index_index.xml
> +    <update handle="inchoo_sample03_index_index"/>
ovaj update ti ne treba, update ti je kao "include" za layoute

2021-08-31 11:44 UTC, jlboban commented on app/code/Inchoo/Sample03/view/frontend/templates/custom/weight.phtml
> +            <?php // phpcs:ignore ?>
jure@jure-G752VM:~/docker/m2$ codecheck

FILE: ...code/Inchoo/Sample03/view/frontend/templates/custom/weight.phtml
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 11 | WARNING | Variable $escaper is undefined.
    |         | (VariableAnalysis.CodeAnalysis.VariableAnalysis.UndefinedVariable)
----------------------------------------------------------------------

2021-09-03 11:26 UTC, tnikcevs approved these changes

2021-09-03 20:11 UTC, ivanmatozan approved these changes

2021-09-06 12:15 UTC, merged