Sample06 tasks
jlboban/m2 pull request #8
Opened 2021-09-07 06:37 UTC by jlboban

2021-09-07 10:15 UTC, tnikcevs requested changes

2021-09-07 10:15 UTC, tnikcevs commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +            $postcode->delete();
ima li $collection metodu delete mozda?

2021-09-07 10:15 UTC, tnikcevs commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +class MassDelete extends \Magento\Backend\App\Action implements HttpPostActionInterface
mozda ovdje manje bitno, ali nek kratak opis funkcije klase bude navika

2021-09-09 12:26 UTC, ivanmatozan requested changes

2021-09-09 12:26 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/etc/acl.xml
> +                            <resource id="Inchoo_Sample06::edit" title="Edit" sortOrder="200" />
nisi morao ovoliko detalno specifirati resource, bio je dovoljan i `Inchoo_Sample06::postcode` :)
Nije greška, ne moraš ništa mijenjati

2021-09-09 12:26 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/Delete.php
> +    const ADMIN_RESOURCE = 'Inchoo_Sample06::postcode';
ako si kreirao Inchoo_Sample06::delete zašto ga ne koristiš? Komentar vrijedi i za ostale view/edit/create

2021-09-09 12:26 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/view/adminhtml/ui_component/postcode_form.xml
> +        <field name="city" formElement="input" sortOrder="6">
uvijek staviš neki između, u ovom slučaju 7 ili 8. Tako u budućnosti omogućiš nekome da doda nešto između tvoga i postojećeg...

2021-09-09 12:26 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +
`declare(strict_types=1);`

2021-09-09 12:26 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +class MassDelete extends \Magento\Backend\App\Action implements HttpPostActionInterface
po meni ne treba komentar, na prvu mi je sve jasno što klasa radi

2021-09-09 12:26 UTC, ivanmatozan commented on app/code/Inchoo/Sample06/Controller/Adminhtml/Postcode/MassDelete.php
> +            $postcode->delete();
CRUD metode na modelu su deprecated i ne bi ih se trebalo koristiti. Treba ići preko resource model ili repository

2021-09-13 06:00 UTC, ivanmatozan approved these changes

2021-09-14 09:54 UTC, tnikcevs approved these changes

2021-09-14 10:02 UTC, merged