Sample07 required tasks
jlboban/m2 pull request #9
Opened 2021-09-09 06:39 UTC by jlboban

Installed sample data

2021-09-09 12:56 UTC, ivanmatozan requested changes

2021-09-09 12:56 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/view/adminhtml/ui_component/customer_listing.xml
> +    <columns name="customer_columns" class="Magento\Customer\Ui\Component\Listing\Columns">
kada modificiraš nešto postojeće ne treba dodavati attribute koje ne mijenjaš (`class`), u ovom slučaju dovoljan ti je `name`

2021-09-09 12:56 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/Setup/Patch/Data/CreateOibCustomerAttribute.php
> +        $eavSetup->updateAttribute($entityType, $attributeCode, [
ovo ti se neće nikada izvršiti jer u teoriji bi ti ovaj patch trebao biti izvršen. Jedini način da ga ponovno pokreneš je da ga obrišeš iz `patch_list` tablice, ali to se radi samo u iznimnim situacijama. Naravno lokalno dok developaš i dok nije završilo na produkciji možeš raditi što hoćeš.

Moraš napraviti novi patch koji radi željenu radnju (pazi na to da ti novi patch dependa na ovaj postojeći)

2021-09-09 12:56 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/Setup/Patch/Data/CreateMobileNumberAddressAttribute.php
> +        $this->createFormAttributeRelations($attributeId);
treba novi patch, ovo se neće izvršiti jer je pretpostavka da je patch već jednom pokrenut. Pogledaj komentar na `CreateOibCustomerAttribute.php`

2021-09-09 12:56 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/Setup/Patch/Data/CreateMobileNumberAddressAttribute.php
> +        $this->moduleDataSetup->getConnection()->insertMultiple($formAttributeTable, $formAttributeData);
još jedan primjer:
https://github.com/ivanmatozan/magento-setup-scripts/blob/8f301d979f8a1c9bd2839b14916d7a4e8144ca94/Setup/InstallData.php#L121-L128

2021-09-09 12:56 UTC, ivanmatozan commented on app/etc/config.php
> +        'Magento_CacheInvalidate' => 1,
otkud ovoliko izmjena u `config.php`?

2021-09-09 12:56 UTC, ivanmatozan commented on composer.json
> +        "magento/composer-root-update-plugin": "~1.1",
zašto si u ovom PR-u instalirao sample data?

2021-09-10 09:25 UTC, jlboban commented on app/etc/config.php
> +        'Magento_CacheInvalidate' => 1,
Zbog instalacije sample data

2021-09-15 06:09 UTC, ivanmatozan requested changes

2021-09-15 06:09 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/Setup/Patch/Data/UpdateOibCustomerAttribute.php
> +        $this->createFormAttributeRelations($attributeId);
ovo je bilo u `CreateOibCustomerAttribute` patchu

2021-09-15 06:09 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/view/frontend/layout/customer_account_create.xml
> +<?xml version="1.0"?>
ovo možeš maknuti, još nisam siguran da se save može napraviti bez observera, a taj sample ide poslije ovoga.

2021-09-15 06:09 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/view/frontend/layout/customer_account_edit.xml
> +<?xml version="1.0"?>
ovo možeš maknuti, još nisam siguran da se save može napraviti bez observera, a taj sample ide poslije ovoga.

2021-09-15 06:09 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/view/frontend/templates/customer/form-additional-info.phtml
> +<?php
ovo možeš maknuti, još nisam siguran da se save može napraviti bez observera, a taj sample ide poslije ovoga.

2021-09-15 06:17 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/Setup/Patch/Data/CreateOibCustomerAttribute.php
> +        $eavSetup->updateAttribute($entityType, $attributeCode, [
ovo nije riješeno

2021-09-15 06:19 UTC, ivanmatozan commented on composer.json
> +        "magento/composer-root-update-plugin": "~1.1",
ok, sada može proći, ali na produkciji gledaj da u PR ne bude smeća i zaostataka

2021-09-15 07:40 UTC, ivanmatozan requested changes

2021-09-15 07:40 UTC, ivanmatozan commented on app/code/Inchoo/Sample07/Setup/Patch/Data/UpdateMobileNumberAddressAttribute.php
> +        $entityType = CustomerMetadataInterface::ENTITY_TYPE_CUSTOMER;
`mobile_number` je `customer_address` attribute

2021-09-16 12:32 UTC, ivanmatozan approved these changes

2021-09-16 13:03 UTC, merged